baseURL = "/"
publishDir = "godaddy"
languageCode = "en-us"
themesDir = "themes"
title = "Stephen's Dev Portfolio"
theme = "hugo-hero-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.RData$"]

[author]
  name = "Stephen"

[params]
  backgroundDefault = "http://www.themindful.life/wp-content/uploads/2019/11/Banff.jpg"
  customDateFormat = "Sun, Jan 2, 2006"
  google_analytics_id=""
  author = "Stephen Holsenbeck"
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "pygments"
  themeColor1text = "black-text"
  themeColor1 = "blue darken-4"
  themeColor2text = "deep-orange-text accent-4"
  showPostSummary = true

  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"

  [params.homepage_meta_tags]
    meta_description = "This is a portfolio chronicling Stephen Holsenbeck's work with the R statistical programming language."
    meta_og_title = "TheMindful.Life - R"
    meta_og_type = "website"
    meta_og_url = "http://themindful.life"
    meta_og_image = "https://i0.wp.com/www.themindful.life/wp-content/uploads/2019/11/YogaPhoto.jpg?resize=245%2C300"
    meta_og_description = "I choose the mindful life - Stephen Holsenbeck's personal website and portfolio."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ascensionasana"

[[menu.main]]
	  name = "Back to main WP site"
	  url = "http://themindful.life"
    weight = 1

[[menu.main]]
	  name = "Portfolio Home"
	  url = "/"
    weight = 2

[[menu.main]]
	  name = "R Experience"
	  url = "/r-experience/"
    weight = 3

[[menu.main]]
    name = "Data Insights - blog"
    url = "/post/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
