baseURL = "http://themindful.life/r/"
publishDir = "godaddy"
languageCode = "en-us"
themesDir = "themes"
title = "Stephen's Dev Portfolio"
theme = "hugo-hero-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.RData$"]

[author]
  name = "Stephen"

[markup]
  defaultMarkdownHandler = "blackfriday"

[params]
  backgroundDefault = "http://www.themindful.life/wp-content/uploads/2019/11/Banff.jpg"
  customDateFormat = "Sun, Jan 2, 2006"
  google_analytics_id=""
  author = "Stephen Holsenbeck"
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "pygments"
  themeColor1text = "black-text"
  themeColor1 = "blue darken-4"
  themeColor2text = "deep-orange-text accent-4"
  showPostSummary = true
  # Set to true to disable code folding
  disable_codefolding = false
  # Set to "hide" or "show" all codes by default
  codefolding_show = "hide"
  # Set to true to exclude the "Show/hide all" button
  codefolding_nobutton = false
  
  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"

  [params.homepage_meta_tags]
    meta_description = "This is a portfolio chronicling Stephen Holsenbeck's work with the R statistical programming language."
    meta_og_title = "TheMindful.Life - R"
    meta_og_type = "website"
    meta_og_url = "http://themindful.life"
    meta_og_image = "https://i0.wp.com/www.themindful.life/wp-content/uploads/2019/11/YogaPhoto.jpg?resize=245%2C300"
    meta_og_description = "I choose the mindful life - Stephen Holsenbeck's personal website and portfolio."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ascensionasana"

[[menu.icon]]
    url = "https://github.com/yogat3ch/"
    name = "fab fa-github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/ascensionasana"
    name = "fab fa-twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/holsenbeck/"
    name = "fab fa-linkedin-in"
    weight = 2

[[menu.icon]]
    url = "https://rpubs.com/yogat3ch/"
    name = "fas fa-registered"
    weight = 3

[[menu.main]]
	  name = "Home"
	  url = "http://themindful.life"
    weight = 1

[[menu.main]]
	  name = "About"
	  url = "http://themindful.life/about"
    weight = 2

[[menu.main]]
    name = "Résumé"
    url = "https://indd.adobe.com/view/447f0a83-67b9-4f08-ba31-d3d9a0f7adec"
    weight = 3

[[menu.main]]
	  name = "Portfolio"
	  url = "/"
    weight = 4

[[menu.main]]
    name = "R (Data Science)" # Drop-down menu entry
    url = "/r-experience/"
    weight = 1
    parent = "Portfolio" # Entry in main menu

[[menu.main]]
    name = "Web Design"
    url = "http://themindful.life/portfolio/"
    weight = 2
    parent = "Portfolio"

[[menu.main]]
	  name = "The Dao of Data (Blog)"
	  url = "/post/"
    weight = 5

[[menu.main]]
	  name = "Contact"
	  url = "http://themindful.life/contact"
    weight = 6

[permalinks]
  post = "/:year/:month/:slug/"
  pages = "/:filename/"
